export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES';
export const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS';
export const SEARCH_REPOSITORIES_FAILED = 'SEARCH_REPOSITORIES_FAILED';
export const SEARCH_REPOSITORIES_CLEAR = 'SEARCH_REPOSITORIES_CLEAR';